Repository jontofront/ecoNET-300-Home-Assistant-Integration, pull requests merged in 2024-12, with the labels that each got.

#113 fixes and refactor for api data fetching
  custom_components/econet300/api.py
Labels: code fix, REFACTOR

#118 fix: improve error handling and logging in get_param_limits method
  custom_components/econet300/api.py
Labels: code fix

#116 Refactor
  custom_components/econet300/const.py
  custom_components/econet300/number.py
  custom_components/econet300/sensor.py
Labels: REFACTOR

#124 Improvements to default value, added new sensor types tempLowerBuffer and tempUpperBuffer
  README.md
  custom_components/econet300/binary_sensor.py
  custom_components/econet300/const.py
  custom_components/econet300/manifest.json
  custom_components/econet300/number.py
  custom_components/econet300/sensor.py
  custom_components/econet300/strings.json
  custom_components/econet300/translations/en.json
  custom_components/econet300/translations/pl.json
Labels: Sensor, code fix, feature, ecoMAX810
